### ISSUE TITLE
Upper limit for domain names of 63 characters

### ISSUE THREAD

**Issue by jam13** [ibotty/openshift-letsencrypt#15]
Spent a few hours scratching my head on this one so I thought it might be worth mentioning in case anyone else hits it. Domain names of more than 64 chars cause both watcher and cron to fail in two places.

- Route generated for validation puts the domain name into a label, these have a limit of 63 chars and so the route creation fails.
- Library used by dehydrated puts the domain name being registered in the CN of the x509 cert, which has an upper limit of 64 chars, so even if you work around the first failure it fails here too.

Certbot issue here: https://github.com/certbot/certbot/issues/1915 (I'm assuming it's the same issue with dehydrated).

**Comment by ibotty** [comment]
Makes sense. It's now exiting early when encountering these long domain names.
